version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672  # AMQP port
      - 15672:15672  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10
      -c shared_preload_libraries=wal2json
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql

  cdc-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    depends_on:
      - postgres
      - rabbitmq
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: inventory
      PG_USER: postgres
      PG_PASS: postgres
      RMQ_HOST: rabbitmq
      RMQ_PORT: 5672
      RMQ_USER: guest
      RMQ_PASS: guest
      QUEUE: dbserver1.public.customers

volumes:
  rabbitmq_data:
